// <auto-generated />
using System;
using Backend.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260522144129_AddChatMessages")]
    partial class AddChatMessages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.Cart", b =>
                {
                    b.Property<int>("IdCart")
                        .HasColumnType("int")
                        .HasColumnName("id_Cart");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_At");

                    b.Property<int>("IdUser")
                        .HasColumnType("int")
                        .HasColumnName("id_User");

                    b.Property<int>("Total")
                        .HasColumnType("int")
                        .HasColumnName("total");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("update_At");

                    b.HasKey("IdCart");

                    b.HasIndex("IdUser");

                    b.ToTable("Cart", (string)null);
                });

            modelBuilder.Entity("Backend.Models.CartFood", b =>
                {
                    b.Property<int>("IdCartFood")
                        .HasColumnType("int")
                        .HasColumnName("id_CartFood");

                    b.Property<int>("IdCart")
                        .HasColumnType("int")
                        .HasColumnName("id_Cart");

                    b.Property<int>("IdFood")
                        .HasColumnType("int")
                        .HasColumnName("id_Food");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("note");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("price");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<decimal>("Total")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("total");

                    b.HasKey("IdCartFood");

                    b.HasIndex("IdCart");

                    b.HasIndex("IdFood");

                    b.ToTable("Cart_Food", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Category", b =>
                {
                    b.Property<int>("IdCategory")
                        .HasColumnType("int")
                        .HasColumnName("id_Category");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("icon");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.HasKey("IdCategory");

                    b.ToTable("Category", (string)null);
                });

            modelBuilder.Entity("Backend.Models.ChatMessage", b =>
                {
                    b.Property<int>("IdMessage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_Message");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMessage"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit")
                        .HasColumnName("is_Read");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("order_Id");

                    b.Property<string>("RoomId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("room_Id");

                    b.Property<int>("SenderId")
                        .HasColumnType("int")
                        .HasColumnName("sender_Id");

                    b.Property<string>("SenderName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("sender_Name");

                    b.Property<string>("SenderRole")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("sender_Role");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("sent_At");

                    b.HasKey("IdMessage");

                    b.ToTable("ChatMessages", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Complaint", b =>
                {
                    b.Property<int>("IdComplaint")
                        .HasColumnType("int")
                        .HasColumnName("id_Complaint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("HandledBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("handled_By");

                    b.Property<int>("IdOrder")
                        .HasColumnType("int")
                        .HasColumnName("id_Order");

                    b.Property<int>("IdUser")
                        .HasColumnType("int")
                        .HasColumnName("id_User");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("image");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("received_At");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("resolved_At");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("type");

                    b.HasKey("IdComplaint");

                    b.HasIndex("IdOrder")
                        .IsUnique();

                    b.HasIndex("IdUser");

                    b.ToTable("Complaint", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Driver", b =>
                {
                    b.Property<int>("IdDriver")
                        .HasColumnType("int")
                        .HasColumnName("id_Driver");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("address");

                    b.Property<decimal>("CurrentLat")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)")
                        .HasColumnName("current_Lat");

                    b.Property<decimal>("CurrentLng")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)")
                        .HasColumnName("current_Lng");

                    b.Property<string>("DescStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("desc_Status");

                    b.Property<string>("ExpRank")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("expRank");

                    b.Property<int>("IdUser")
                        .HasColumnType("int")
                        .HasColumnName("id_User");

                    b.Property<bool>("IsBusy")
                        .HasColumnType("bit")
                        .HasColumnName("is_Busy");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("license_plate");

                    b.Property<decimal>("RateAvg")
                        .HasPrecision(2, 1)
                        .HasColumnType("decimal(2,1)")
                        .HasColumnName("rate_Avg");

                    b.Property<int>("TotalOrders")
                        .HasColumnType("int")
                        .HasColumnName("total_Orders");

                    b.HasKey("IdDriver");

                    b.HasIndex("IdUser")
                        .IsUnique();

                    b.ToTable("Driver", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Food", b =>
                {
                    b.Property<int>("IdFood")
                        .HasColumnType("int")
                        .HasColumnName("id_Food");

                    b.Property<int?>("CookCount")
                        .HasColumnType("int")
                        .HasColumnName("cook_Count");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<decimal?>("Discount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("discount");

                    b.Property<int>("IdCategory")
                        .HasColumnType("int")
                        .HasColumnName("id_Category");

                    b.Property<int>("IdRestaurant")
                        .HasColumnType("int")
                        .HasColumnName("id_Restaurant");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("image");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<int?>("PrepTime")
                        .HasColumnType("int")
                        .HasColumnName("prep_Time");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("price");

                    b.HasKey("IdFood");

                    b.HasIndex("IdCategory");

                    b.HasIndex("IdRestaurant");

                    b.ToTable("Food", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Notification", b =>
                {
                    b.Property<int>("IdNoti")
                        .HasColumnType("int")
                        .HasColumnName("id_Noti");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("body");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_At");

                    b.Property<int>("IdUser")
                        .HasColumnType("int")
                        .HasColumnName("id_User");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit")
                        .HasColumnName("is_Read");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("orderId");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("title");

                    b.HasKey("IdNoti");

                    b.HasIndex("IdUser");

                    b.ToTable("Notification", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Order", b =>
                {
                    b.Property<int>("IdOrder")
                        .HasColumnType("int")
                        .HasColumnName("id_Order");

                    b.Property<string>("CancelReason")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cancel_Reason");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_At");

                    b.Property<string>("DeliveryAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("delivery_Address");

                    b.Property<decimal?>("DeliveryLat")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)")
                        .HasColumnName("delivery_Lat");

                    b.Property<decimal?>("DeliveryLng")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)")
                        .HasColumnName("delivery_Lng");

                    b.Property<decimal>("Discount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("discount");

                    b.Property<decimal>("FinalTotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("finalTotal");

                    b.Property<decimal>("FoodAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("food_Amount");

                    b.Property<int?>("IdDriver")
                        .HasColumnType("int")
                        .HasColumnName("id_Driver");

                    b.Property<int>("IdRestaurant")
                        .HasColumnType("int")
                        .HasColumnName("id_Restaurant");

                    b.Property<int>("IdUser")
                        .HasColumnType("int")
                        .HasColumnName("id_User");

                    b.Property<int?>("IdVoucher")
                        .HasColumnType("int")
                        .HasColumnName("id_Voucher");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("note");

                    b.Property<string>("OrderCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("order_Code");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("paymentMethod");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("paymentStatus");

                    b.Property<decimal>("ShippingFee")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("shippingFee");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_At");

                    b.HasKey("IdOrder");

                    b.HasIndex("IdDriver");

                    b.HasIndex("IdRestaurant");

                    b.HasIndex("IdUser");

                    b.HasIndex("IdVoucher");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("Backend.Models.OrderFood", b =>
                {
                    b.Property<int>("IdOrderFood")
                        .HasColumnType("int")
                        .HasColumnName("id_OrderFood");

                    b.Property<int>("IdFood")
                        .HasColumnType("int")
                        .HasColumnName("id_Food");

                    b.Property<int>("IdOrder")
                        .HasColumnType("int")
                        .HasColumnName("id_Order");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("note");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("total_Price");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("unit_Price");

                    b.HasKey("IdOrderFood");

                    b.HasIndex("IdFood");

                    b.HasIndex("IdOrder");

                    b.ToTable("Order_Food", (string)null);
                });

            modelBuilder.Entity("Backend.Models.OrderPromotion", b =>
                {
                    b.Property<int>("IdOrder")
                        .HasColumnType("int")
                        .HasColumnName("id_Order");

                    b.Property<int>("IdPromo")
                        .HasColumnType("int")
                        .HasColumnName("id_Promo");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("discount_Amount");

                    b.HasKey("IdOrder", "IdPromo");

                    b.HasIndex("IdPromo");

                    b.ToTable("Order_Promotion", (string)null);
                });

            modelBuilder.Entity("Backend.Models.PaymentMethod", b =>
                {
                    b.Property<int>("IdTransaction")
                        .HasColumnType("int")
                        .HasColumnName("id_Transaction");

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("amount");

                    b.Property<int>("IdOrder")
                        .HasColumnType("int")
                        .HasColumnName("id_Order");

                    b.Property<int>("IdUser")
                        .HasColumnType("int")
                        .HasColumnName("id_User");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("method");

                    b.HasKey("IdTransaction");

                    b.HasIndex("IdOrder")
                        .IsUnique();

                    b.HasIndex("IdUser");

                    b.ToTable("PaymentMethod", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Promotion", b =>
                {
                    b.Property<int>("IdPromo")
                        .HasColumnType("int")
                        .HasColumnName("id_Promo");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("end_Date");

                    b.Property<int>("IdRestaurant")
                        .HasColumnType("int")
                        .HasColumnName("id_Restaurant");

                    b.Property<decimal>("MaxDiscount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("max_Discount");

                    b.Property<decimal>("MinOrderValue")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("min_OrderValue");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("start_Date");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("type");

                    b.Property<int>("UsageLimit")
                        .HasColumnType("int")
                        .HasColumnName("usage_Limit");

                    b.Property<int>("UsedCount")
                        .HasColumnType("int")
                        .HasColumnName("used_Count");

                    b.Property<decimal>("Value")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("value");

                    b.HasKey("IdPromo");

                    b.HasIndex("IdRestaurant");

                    b.ToTable("Promotion", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Restaurant", b =>
                {
                    b.Property<int>("IdRestaurant")
                        .HasColumnType("int")
                        .HasColumnName("id_Restaurant");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("address");

                    b.Property<TimeSpan>("CloseTime")
                        .HasColumnType("time")
                        .HasColumnName("closeTime");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("image");

                    b.Property<decimal>("Lat")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)")
                        .HasColumnName("lat");

                    b.Property<decimal>("Lng")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)")
                        .HasColumnName("lng");

                    b.Property<string>("NameRestaurant")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name_Restaurant");

                    b.Property<TimeSpan>("OpenTime")
                        .HasColumnType("time")
                        .HasColumnName("openTime");

                    b.HasKey("IdRestaurant");

                    b.ToTable("Restaurant", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Review", b =>
                {
                    b.Property<int>("IdReview")
                        .HasColumnType("int")
                        .HasColumnName("id_Review");

                    b.Property<string>("CommentForRes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("comment_ForRes");

                    b.Property<string>("CommentForShipper")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("comment_ForShipper");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_At");

                    b.Property<float>("DriverRating")
                        .HasColumnType("real")
                        .HasColumnName("driver_rating");

                    b.Property<float>("FoodRating")
                        .HasColumnType("real")
                        .HasColumnName("food_rating");

                    b.Property<int>("IdOrder")
                        .HasColumnType("int")
                        .HasColumnName("id_Order");

                    b.Property<int>("IdRestaurant")
                        .HasColumnType("int")
                        .HasColumnName("id_Restaurant");

                    b.Property<int>("IdUser")
                        .HasColumnType("int")
                        .HasColumnName("id_User");

                    b.HasKey("IdReview");

                    b.HasIndex("IdOrder")
                        .IsUnique();

                    b.HasIndex("IdRestaurant");

                    b.HasIndex("IdUser");

                    b.ToTable("Review", (string)null);
                });

            modelBuilder.Entity("Backend.Models.ReviewFood", b =>
                {
                    b.Property<int>("IdReviewFood")
                        .HasColumnType("int")
                        .HasColumnName("id_ReviewFood");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("comment");

                    b.Property<int>("IdFood")
                        .HasColumnType("int")
                        .HasColumnName("id_Food");

                    b.Property<int>("IdReview")
                        .HasColumnType("int")
                        .HasColumnName("id_Review");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("image");

                    b.Property<float>("Rating")
                        .HasColumnType("real")
                        .HasColumnName("rating");

                    b.Property<string>("Video")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("video");

                    b.HasKey("IdReviewFood");

                    b.HasIndex("IdFood");

                    b.HasIndex("IdReview");

                    b.ToTable("Review_Food", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Role", b =>
                {
                    b.Property<int>("IdRole")
                        .HasColumnType("int")
                        .HasColumnName("id_Role");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("role_Name");

                    b.HasKey("IdRole");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Backend.Models.SystemLog", b =>
                {
                    b.Property<int>("IdLog")
                        .HasColumnType("int")
                        .HasColumnName("id_Log");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_At");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("entity");

                    b.Property<int>("EntityId")
                        .HasColumnType("int")
                        .HasColumnName("entity_Id");

                    b.Property<int>("IdUser")
                        .HasColumnType("int")
                        .HasColumnName("id_User");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ip_Address");

                    b.Property<string>("NewValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("new_Value");

                    b.Property<string>("OldValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("old_Value");

                    b.HasKey("IdLog");

                    b.HasIndex("IdUser");

                    b.ToTable("SystemLog", (string)null);
                });

            modelBuilder.Entity("Backend.Models.User", b =>
                {
                    b.Property<int>("IdUser")
                        .HasColumnType("int")
                        .HasColumnName("id_User");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("address");

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("avatar");

                    b.Property<float?>("CancelRate")
                        .HasColumnType("real")
                        .HasColumnName("cancel_Rate");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_At");

                    b.Property<decimal?>("CurrentLat")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)")
                        .HasColumnName("current_Lat");

                    b.Property<decimal?>("CurrentLng")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)")
                        .HasColumnName("current_Lng");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fullName");

                    b.Property<int>("IdRole")
                        .HasColumnType("int")
                        .HasColumnName("id_Role");

                    b.Property<DateTime?>("LastOnline")
                        .HasColumnType("datetime2")
                        .HasColumnName("lastOnline");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("phone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("username");

                    b.HasKey("IdUser");

                    b.HasIndex("IdRole");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Voucher", b =>
                {
                    b.Property<int>("IdVoucher")
                        .HasColumnType("int")
                        .HasColumnName("id_Voucher");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("code");

                    b.Property<DateTime>("Expiry")
                        .HasColumnType("datetime2")
                        .HasColumnName("expiry");

                    b.Property<int>("IdUser")
                        .HasColumnType("int")
                        .HasColumnName("id_User");

                    b.Property<bool>("Used")
                        .HasColumnType("bit")
                        .HasColumnName("used");

                    b.Property<decimal>("Value")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("value");

                    b.HasKey("IdVoucher");

                    b.HasIndex("IdUser");

                    b.ToTable("Voucher", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Cart", b =>
                {
                    b.HasOne("Backend.Models.User", "User")
                        .WithMany("Carts")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Models.CartFood", b =>
                {
                    b.HasOne("Backend.Models.Cart", "Cart")
                        .WithMany("CartFoods")
                        .HasForeignKey("IdCart")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Food", "Food")
                        .WithMany("CartFoods")
                        .HasForeignKey("IdFood")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Food");
                });

            modelBuilder.Entity("Backend.Models.Complaint", b =>
                {
                    b.HasOne("Backend.Models.Order", "Order")
                        .WithOne("Complaint")
                        .HasForeignKey("Backend.Models.Complaint", "IdOrder")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.User", "User")
                        .WithMany("Complaints")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Models.Driver", b =>
                {
                    b.HasOne("Backend.Models.User", "User")
                        .WithOne("Driver")
                        .HasForeignKey("Backend.Models.Driver", "IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Models.Food", b =>
                {
                    b.HasOne("Backend.Models.Category", "Category")
                        .WithMany("Foods")
                        .HasForeignKey("IdCategory")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Restaurant", "Restaurant")
                        .WithMany("Foods")
                        .HasForeignKey("IdRestaurant")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("Backend.Models.Notification", b =>
                {
                    b.HasOne("Backend.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Models.Order", b =>
                {
                    b.HasOne("Backend.Models.Driver", "Driver")
                        .WithMany("Orders")
                        .HasForeignKey("IdDriver");

                    b.HasOne("Backend.Models.Restaurant", "Restaurant")
                        .WithMany("Orders")
                        .HasForeignKey("IdRestaurant")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Voucher", "Voucher")
                        .WithMany()
                        .HasForeignKey("IdVoucher");

                    b.Navigation("Driver");

                    b.Navigation("Restaurant");

                    b.Navigation("User");

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("Backend.Models.OrderFood", b =>
                {
                    b.HasOne("Backend.Models.Food", "Food")
                        .WithMany("OrderFoods")
                        .HasForeignKey("IdFood")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Order", "Order")
                        .WithMany("OrderFoods")
                        .HasForeignKey("IdOrder")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Backend.Models.OrderPromotion", b =>
                {
                    b.HasOne("Backend.Models.Order", "Order")
                        .WithMany("OrderPromotions")
                        .HasForeignKey("IdOrder")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Promotion", "Promotion")
                        .WithMany("OrderPromotions")
                        .HasForeignKey("IdPromo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Promotion");
                });

            modelBuilder.Entity("Backend.Models.PaymentMethod", b =>
                {
                    b.HasOne("Backend.Models.Order", "Order")
                        .WithOne("PaymentMethodEntity")
                        .HasForeignKey("Backend.Models.PaymentMethod", "IdOrder")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.User", "User")
                        .WithMany("PaymentMethods")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Models.Promotion", b =>
                {
                    b.HasOne("Backend.Models.Restaurant", "Restaurant")
                        .WithMany("Promotions")
                        .HasForeignKey("IdRestaurant")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("Backend.Models.Review", b =>
                {
                    b.HasOne("Backend.Models.Order", "Order")
                        .WithOne("Review")
                        .HasForeignKey("Backend.Models.Review", "IdOrder")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Restaurant", "Restaurant")
                        .WithMany("Reviews")
                        .HasForeignKey("IdRestaurant")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Restaurant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Models.ReviewFood", b =>
                {
                    b.HasOne("Backend.Models.Food", "Food")
                        .WithMany("ReviewFoods")
                        .HasForeignKey("IdFood")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Review", "Review")
                        .WithMany("ReviewFoods")
                        .HasForeignKey("IdReview")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");

                    b.Navigation("Review");
                });

            modelBuilder.Entity("Backend.Models.SystemLog", b =>
                {
                    b.HasOne("Backend.Models.User", "User")
                        .WithMany("SystemLogs")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Models.User", b =>
                {
                    b.HasOne("Backend.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("IdRole")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Backend.Models.Voucher", b =>
                {
                    b.HasOne("Backend.Models.User", "User")
                        .WithMany("Vouchers")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Models.Cart", b =>
                {
                    b.Navigation("CartFoods");
                });

            modelBuilder.Entity("Backend.Models.Category", b =>
                {
                    b.Navigation("Foods");
                });

            modelBuilder.Entity("Backend.Models.Driver", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Backend.Models.Food", b =>
                {
                    b.Navigation("CartFoods");

                    b.Navigation("OrderFoods");

                    b.Navigation("ReviewFoods");
                });

            modelBuilder.Entity("Backend.Models.Order", b =>
                {
                    b.Navigation("Complaint")
                        .IsRequired();

                    b.Navigation("OrderFoods");

                    b.Navigation("OrderPromotions");

                    b.Navigation("PaymentMethodEntity")
                        .IsRequired();

                    b.Navigation("Review")
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.Models.Promotion", b =>
                {
                    b.Navigation("OrderPromotions");
                });

            modelBuilder.Entity("Backend.Models.Restaurant", b =>
                {
                    b.Navigation("Foods");

                    b.Navigation("Orders");

                    b.Navigation("Promotions");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Backend.Models.Review", b =>
                {
                    b.Navigation("ReviewFoods");
                });

            modelBuilder.Entity("Backend.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Backend.Models.User", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("Complaints");

                    b.Navigation("Driver")
                        .IsRequired();

                    b.Navigation("Notifications");

                    b.Navigation("Orders");

                    b.Navigation("PaymentMethods");

                    b.Navigation("Reviews");

                    b.Navigation("SystemLogs");

                    b.Navigation("Vouchers");
                });
#pragma warning restore 612, 618
        }
    }
}
